
scrape_task:
  description: >
    Scrape through all the links and capture all the information on the page whether dynamic or static

    Here are the Links: {urls}
  expected_output: >
    a file containg all the information in the text form in raw form
  agent: scraper


