
scrape_task:
  description: >
    Scrape through all the links provided to get the information about starup

    Here are the Links: {urls}
  expected_output: >
    All the information related to team
  agent: scraper


