version: '3.1'

services:
  db:
    image: postgres
    container_name: rubrics-ui-db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: rubrics_ui_localhost
    ports:
      - "5432:5432"
    volumes:
        - ./data:/var/lib/postgresql/data
        - ./init.sql:/docker-entrypoint-initdb.d/init.sql
