name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'docs/**'

jobs:
  lint_and_prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Academy - Install dependencies
        run: cd academy-ui && yarn

      - name: Academy - Run ESLint
        run: cd academy-ui && yarn lint

      - name: Academy - Run Prettier
        run: cd academy-ui && yarn prettier-check

      - name: Academy - TSC
        run: cd academy-ui && yarn tsc

      - name: Academy - NEXT Build
        run: cd academy-ui && yarn build

      - name: Base UI - Install dependencies
        run: cd base-ui && yarn

      - name: Base UI - Run ESLint
        run: cd base-ui && yarn lint

      - name: Base UI - Run Prettier
        run: cd base-ui && yarn prettier-check

      - name: Base UI - TSC
        run: cd base-ui && yarn compile

      - name: BASE UI - NEXT Build
        run: cd base-ui && yarn build

      - name: Rubrics UI - Install dependencies
        run: cd rubrics-ui && yarn

      - name: Rubrics UI - Run ESLint
        run: cd rubrics-ui && yarn lint

      - name: Rubrics UI - Run Prettier
        run: cd rubrics-ui && yarn prettier-check

      - name: Rubrics UI - TSC
        run: cd rubrics-ui && yarn compile

      - name: Rubrics UI - NEXT Build
        run: cd rubrics-ui && yarn build

