name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint_and_prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Install dependencies
        run: cd academy-ui && yarn

      - name: Run ESLint
        run: cd academy-ui && yarn lint

      - name: Run Prettier
        run: cd academy-ui && yarn prettier-check

      - name: TSC
        run: cd academy-ui && yarn tsc
